# Generated by Django 3.1.5 on 2021-12-22 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deck',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, size=236),
        ),
    ]
