# Generated by Django 3.1.5 on 2021-12-22 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211222_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deck',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=None, size=236),
        ),
    ]
